# -*- coding: utf-8 -*-
"""derangement_integer_and_string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TquNQesFEoHL9CQHCXaeQhZgCFe_qjAH
"""

import numpy as np
import pandas as pd

"""作業1"""

def derangement(n):
  if n ==1:
    return 0
  elif n ==2:
    return 1
  else:
    return (n-1)*(derangement(n-1)+derangement(n-2))

derangement(int(input()))

"""作業2"""

def ans(srr,stt):
    if(len(stt) < len(srr)):
        for cc in srr:
            if not cc in stt:
                stt.append(cc)
                ans(srr, stt) 
                stt.remove(cc)
    else:
      if all(srr[i] != stt[i] for i in range(len(stt))):
        print(stt)
sr= "ABCDE"
st= list()
ans(sr,st)